//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAN()
        {
            this.BAN_BANAN = new HashSet<BAN_BANAN>();
        }
    
        public int MaBan { get; set; }
        public string ViTri { get; set; }
        public Nullable<byte> SoGheThongThuong { get; set; }
        public Nullable<byte> MaCN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_BANAN> BAN_BANAN { get; set; }
        public virtual CHINHANH CHINHANH { get; set; }
    }
}
