//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_BANAN
    {
        public int MaBanAn { get; set; }
        public int MaBan { get; set; }
        public string TrangThaiBan { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual BANAN BANAN { get; set; }
    }
}
