//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANAN_MONAN
    {
        public int MaBanAn { get; set; }
        public int MaMon { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual MONAN MONAN { get; set; }
    }
}
