//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOPHAN_CHINHANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOPHAN_CHINHANH()
        {
            this.LICHSULAMVIECs = new HashSet<LICHSULAMVIEC>();
        }
    
        public byte MaBoPhan { get; set; }
        public Nullable<int> MucLuongThangCoBan { get; set; }
        public byte MaCN { get; set; }
        public Nullable<byte> NgayLamViecTrongTuan { get; set; }
        public Nullable<decimal> GioLamViecTrongNgay { get; set; }
    
        public virtual BOPHAN BOPHAN { get; set; }
        public virtual CHINHANH CHINHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSULAMVIEC> LICHSULAMVIECs { get; set; }
    }
}
