//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHINHANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHINHANH()
        {
            this.BANs = new HashSet<BAN>();
            this.BOPHAN_CHINHANH = new HashSet<BOPHAN_CHINHANH>();
            this.THUCDONs = new HashSet<THUCDON>();
        }
    
        public byte MaCN { get; set; }
        public string TenChiNhanh { get; set; }
        public Nullable<System.TimeSpan> ThoiGianMo { get; set; }
        public Nullable<System.TimeSpan> ThoiGianDong { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public int MaKV { get; set; }
        public Nullable<bool> BaiDoXeHoi { get; set; }
        public Nullable<bool> BaiDoXeMay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN> BANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOPHAN_CHINHANH> BOPHAN_CHINHANH { get; set; }
        public virtual KHUVUC KHUVUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUCDON> THUCDONs { get; set; }
    }
}
