//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIADICHVU
    {
        public int MaDanhGia { get; set; }
        public Nullable<double> DiemPhucVu { get; set; }
        public Nullable<double> DiemChiNhanh { get; set; }
        public Nullable<double> DiemMonAn { get; set; }
        public Nullable<double> DiemKhongGian { get; set; }
        public int MaHD { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
