//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.DANHGIADICHVUs = new HashSet<DANHGIADICHVU>();
        }
    
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<double> SoTien { get; set; }
        public int MaThe { get; set; }
        public int MaBanAn { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual BANAN BANAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIADICHVU> DANHGIADICHVUs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THETHANHVIEN THETHANHVIEN { get; set; }
    }
}
