//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSULAMVIEC
    {
        public int MaNV { get; set; }
        public byte MaBoPhan { get; set; }
        public byte MaCN { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
    
        public virtual BOPHAN_CHINHANH BOPHAN_CHINHANH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
