//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public int MaLuong { get; set; }
        public Nullable<int> LuongCoBan { get; set; }
        public Nullable<double> Thuong { get; set; }
        public Nullable<double> KhauTru { get; set; }
        public Nullable<double> ChuKyNhan { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public int MaNV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
