//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class THETHANHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THETHANHVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MaThe { get; set; }
        public Nullable<int> LoaiThe { get; set; }
        public Nullable<int> DiemTichLuy { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayDatHangThe { get; set; }
        public int MaKH { get; set; }
        public int NhanVienLapThe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAITHE LOAITHE1 { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
